"""Curated Steam game catalog used by the Steam install endpoints.

The catalog is kept intentionally small so we can document and test the
images we ship. To make it easier to grow the list without touching code we
also merge in optional JSON descriptors located under backend/data/steam_games.
"""

from __future__ import annotations

import json
from pathlib import Path


BASE_STEAM_GAMES = {
    "palworld": {
        "display_name": "Palworld",
        "steam_appid": 1623730,
        "category": "Survival",
        "summary": "Co-op creature survival shooter with heavy CPU load on busy worlds.",
        "notes": "Set a strong admin password and monitor CPU usage as bases grow.",
        "default_name": "palworld",
        "image": "thijsvanloef/palworld-server-docker:latest",
        "ports": [
            {"container": 8211, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "TZ": "UTC",
            "SERVER_NAME": "Palworld Server",
            "SERVER_PASSWORD": "change-me",
            "ADMIN_PASSWORD": "admin",
        },
        "volume": {"container": "/palworld"},
        "server_commands": {
            "save": "/Save",
            "stop": "/DoExit",
            "shutdown": "/Shutdown 30 Server shutting down in 30 seconds",
            "broadcast": "/Broadcast {message}",
        },
        "game_settings": {
            "config_file": "Pal/Saved/Config/LinuxServer/PalWorldSettings.ini",
            "config_format": "ini-oneline",
            "config_section": "/Script/Pal.PalGameWorldSettings",
            "config_key": "OptionSettings",
            "settings": [
                {"key": "Difficulty", "label": "Difficulty", "type": "select", "options": ["None", "Easy", "Normal", "Hard"], "default": "None", "env_var": "DIFFICULTY"},
                {"key": "DayTimeSpeedRate", "label": "Day Time Speed", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "DAYTIME_SPEEDRATE"},
                {"key": "NightTimeSpeedRate", "label": "Night Time Speed", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "NIGHTTIME_SPEEDRATE"},
                {"key": "ExpRate", "label": "EXP Rate", "type": "float", "min": 0.1, "max": 20.0, "default": 1.0, "env_var": "EXP_RATE"},
                {"key": "PalCaptureRate", "label": "Pal Capture Rate", "type": "float", "min": 0.5, "max": 2.0, "default": 1.0, "env_var": "PAL_CAPTURE_RATE"},
                {"key": "PalSpawnNumRate", "label": "Pal Spawn Rate", "type": "float", "min": 0.5, "max": 3.0, "default": 1.0, "env_var": "PAL_SPAWN_NUM_RATE"},
                {"key": "PalDamageRateAttack", "label": "Pal Attack Damage", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PAL_DAMAGE_RATE_ATTACK"},
                {"key": "PalDamageRateDefense", "label": "Pal Defense", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PAL_DAMAGE_RATE_DEFENSE"},
                {"key": "PlayerDamageRateAttack", "label": "Player Attack Damage", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PLAYER_DAMAGE_RATE_ATTACK"},
                {"key": "PlayerDamageRateDefense", "label": "Player Defense", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PLAYER_DAMAGE_RATE_DEFENSE"},
                {"key": "PlayerStomachDecreaceRate", "label": "Hunger Depletion Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PLAYER_STOMACH_DECREASE_RATE"},
                {"key": "PlayerStaminaDecreaceRate", "label": "Stamina Depletion Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PLAYER_STAMINA_DECREASE_RATE"},
                {"key": "PlayerAutoHPRegeneRate", "label": "Player HP Regen Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PLAYER_AUTO_HP_REGEN_RATE"},
                {"key": "PlayerAutoHpRegeneRateInSleep", "label": "HP Regen Rate (Sleeping)", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP"},
                {"key": "PalStomachDecreaceRate", "label": "Pal Hunger Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PAL_STOMACH_DECREASE_RATE"},
                {"key": "PalAutoHPRegeneRate", "label": "Pal HP Regen Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "PAL_AUTO_HP_REGEN_RATE"},
                {"key": "BuildObjectDamageRate", "label": "Structure Damage Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0, "env_var": "BUILD_OBJECT_DAMAGE_RATE"},
                {"key": "BuildObjectDeteriorationDamageRate", "label": "Structure Deterioration Rate", "type": "float", "min": 0.0, "max": 10.0, "default": 1.0, "env_var": "BUILD_OBJECT_DETERIORATION_DAMAGE_RATE"},
                {"key": "CollectionDropRate", "label": "Gatherable Drop Rate", "type": "float", "min": 0.5, "max": 5.0, "default": 1.0, "env_var": "COLLECTION_DROP_RATE"},
                {"key": "CollectionObjectHpRate", "label": "Gatherable HP Rate", "type": "float", "min": 0.5, "max": 3.0, "default": 1.0, "env_var": "COLLECTION_OBJECT_HP_RATE"},
                {"key": "CollectionObjectRespawnSpeedRate", "label": "Gatherable Respawn Speed", "type": "float", "min": 0.5, "max": 3.0, "default": 1.0, "env_var": "COLLECTION_OBJECT_RESPAWN_SPEED_RATE"},
                {"key": "EnemyDropItemRate", "label": "Enemy Drop Rate", "type": "float", "min": 0.5, "max": 5.0, "default": 1.0, "env_var": "ENEMY_DROP_ITEM_RATE"},
                {"key": "DeathPenalty", "label": "Death Penalty", "type": "select", "options": ["None", "Item", "ItemAndEquipment", "All"], "default": "All", "env_var": "DEATH_PENALTY"},
                {"key": "bEnablePlayerToPlayerDamage", "label": "PvP Damage", "type": "bool", "default": False, "env_var": "ENABLE_PLAYER_TO_PLAYER_DAMAGE"},
                {"key": "bEnableFriendlyFire", "label": "Friendly Fire", "type": "bool", "default": False, "env_var": "ENABLE_FRIENDLY_FIRE"},
                {"key": "bEnableInvaderEnemy", "label": "Enable Raids", "type": "bool", "default": True, "env_var": "ENABLE_INVADER_ENEMY"},
                {"key": "bActiveUNKO", "label": "Active UNKO", "type": "bool", "default": False, "env_var": "ACTIVE_UNKO"},
                {"key": "bIsPvP", "label": "PvP Mode", "type": "bool", "default": False, "env_var": "IS_PVP"},
                {"key": "bCanPickupOtherGuildDeathPenaltyDrop", "label": "Pickup Other Guild Drops", "type": "bool", "default": False, "env_var": "CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP"},
                {"key": "GuildPlayerMaxNum", "label": "Max Guild Members", "type": "int", "min": 1, "max": 100, "default": 20, "env_var": "GUILD_PLAYER_MAX_NUM"},
                {"key": "BaseCampMaxNum", "label": "Max Base Camps", "type": "int", "min": 1, "max": 128, "default": 128, "env_var": "BASE_CAMP_MAX_NUM"},
                {"key": "BaseCampWorkerMaxNum", "label": "Max Base Workers", "type": "int", "min": 1, "max": 20, "default": 15, "env_var": "BASE_CAMP_WORKER_MAX_NUM"},
                {"key": "DropItemMaxNum", "label": "Max Dropped Items", "type": "int", "min": 0, "max": 5000, "default": 3000, "env_var": "DROP_ITEM_MAX_NUM"},
                {"key": "ServerPlayerMaxNum", "label": "Max Players", "type": "int", "min": 1, "max": 32, "default": 32, "env_var": "PLAYERS"},
            ],
        },
    },
    "project_zomboid": {
        "display_name": "Project Zomboid",
        "steam_appid": 108600,
        "category": "Survival",
        "summary": "Isometric zombie survival with persistent worlds and RCON support.",
        "notes": "Watch RAM usage for large maps. First start downloads ~2 GB.",
        "default_name": "zomboid",
        "image": "ghcr.io/ich777/steamcmd:projectzomboid",
        "ports": [
            {"container": 16261, "protocol": "udp"},
            {"container": 16262, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "380870",
            "GAME_PARAMS": "-adminpassword change-me -servername Zomboid-Server",
            "GAME_PORT": 16261,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
        "server_commands": {
            "save": "save",
            "stop": "quit",
            "broadcast": "servermsg \"{message}\"",
        },
    },
    "valheim": {
        "display_name": "Valheim",
        "steam_appid": 892970,
        "category": "Survival",
        "summary": "Popular Viking survival sandbox supporting up to 10 players.",
        "notes": "Configure world name and server password; open UDP ports 2456-2458.",
        "default_name": "valheim",
        "image": "lloesche/valheim-server:latest",
        "ports": [
            {"container": 2456, "protocol": "udp"},
            {"container": 2457, "protocol": "udp"},
            {"container": 2458, "protocol": "udp"},
        ],
        "env": {
            "SERVER_NAME": "Valheim Server",
            "WORLD_NAME": "Dedicated",
            "SERVER_PASS": "change-me",
        },
        "volume": {"container": "/config"},
        "server_commands": {
            "save": "save",
            "stop_method": "signal",  # Uses SIGINT (Ctrl+C)
            "notes": "Valheim uses SIGINT for graceful shutdown, no RCON.",
        },
        "game_settings": {
            "config_file": "valheim_server.env",
            "config_format": "env",
            "settings": [
                {"key": "SERVER_NAME", "label": "Server Name", "type": "string", "default": "Valheim Server"},
                {"key": "WORLD_NAME", "label": "World Name", "type": "string", "default": "Dedicated"},
                {"key": "SERVER_PASS", "label": "Server Password", "type": "string", "default": ""},
                {"key": "SERVER_PUBLIC", "label": "Public Server", "type": "bool", "default": True},
                {"key": "BACKUPS_MAX_COUNT", "label": "Max Backup Count", "type": "int", "min": 0, "max": 100, "default": 4},
                {"key": "BACKUPS_INTERVAL", "label": "Backup Interval (seconds)", "type": "int", "min": 600, "max": 86400, "default": 43200},
            ],
        },
    },
    "tmodloader": {
        "display_name": "Terraria (tModLoader)",
        "steam_appid": 105600,
        "category": "Sandbox",
        "summary": "Modded Terraria server via tModLoader with SteamCMD builds.",
        "notes": "Set world seed, max players, and password as desired.",
        "default_name": "tmodloader",
        "image": "ghcr.io/beardedio/terraria:latest",
        "ports": [
            {"container": 7777, "protocol": "tcp"},
        ],
        "env": {
            "WORLD_NAME": "Dedicated",
            "MAX_PLAYERS": 8,
            "TYPE": "tmodloader",
            "WORLD_FILENAME": "Dedicated.wld",
            "WORLD_SIZE": 3,
            "WORLD_DIFFICULTY": 1,
            "WORLD_SEED": "",
        },
        "volume": {"container": "/config"},
    },
    "cs2": {
        "display_name": "Counter-Strike 2",
        "steam_appid": 730,
        "category": "Shooter",
        "summary": "Dedicated CS2 server with tickrate and RCON configuration.",
        "notes": "Downloads ~35 GB on first start. A Game Server Login Token (SRCDS_TOKEN) is REQUIRED for the server to be publicly listed — get one at steamcommunity.com/dev/managegameservers.",
        "default_name": "cs2",
        "image": "cm2network/cs2:latest",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27015, "protocol": "tcp"},
        ],
        "env": {
            "SRCDS_RCONPW": "change-me",
            "SRCDS_PW": "",
            "SRCDS_TOKEN": "",
            "SRCDS_FPSMAX": 300,
            "SRCDS_TICKRATE": 128,
            "CS2_GAMETYPE": 0,
            "CS2_GAMEMODE": 1,
            "CS2_MAPGROUP": "mg_active",
            "CS2_STARTMAP": "de_dust2",
            "CS2_MAXPLAYERS": 10,
        },
        "volume": {"container": "/home/steam/cs2-dedicated"},
        "server_commands": {
            "stop": "quit",
            "restart_match": "mp_restartgame 1",
            "broadcast": "say {message}",
            "kick": "kick {player}",
            "ban": "banid {duration} {steamid}",
            "changelevel": "changelevel {map}",
        },
        "game_settings": {
            "config_file": "game/csgo/cfg/server.cfg",
            "config_format": "keyvalue",
            "settings": [
                {"key": "hostname", "label": "Server Name", "type": "string", "default": "CS2 Server"},
                {"key": "sv_password", "label": "Server Password", "type": "string", "default": ""},
                {"key": "rcon_password", "label": "RCON Password", "type": "string", "default": ""},
                {"key": "sv_cheats", "label": "Enable Cheats", "type": "bool", "default": False},
                {"key": "mp_autoteambalance", "label": "Auto Team Balance", "type": "bool", "default": True},
                {"key": "mp_roundtime", "label": "Round Time (min)", "type": "float", "min": 1.0, "max": 60.0, "default": 5.0},
                {"key": "mp_freezetime", "label": "Freeze Time (sec)", "type": "int", "min": 0, "max": 60, "default": 15},
                {"key": "mp_buytime", "label": "Buy Time (sec)", "type": "int", "min": 0, "max": 120, "default": 20},
                {"key": "mp_maxrounds", "label": "Max Rounds", "type": "int", "min": 1, "max": 100, "default": 30},
                {"key": "bot_quota", "label": "Bot Count", "type": "int", "min": 0, "max": 20, "default": 0},
            ],
        },
    },
    "factorio": {
        "display_name": "Factorio",
        "steam_appid": 427520,
        "category": "Simulation",
        "summary": "Automation factory builder with deterministic saves and mods.",
        "notes": "Enable save/backups and set a server password if needed.",
        "default_name": "factorio",
        "image": "factoriotools/factorio:stable",
        "ports": [
            {"container": 34197, "protocol": "udp"},
        ],
        "env": {
            "SERVER_NAME": "Factorio Server",
            "SERVER_PASSWORD": "",
            "LOAD_LATEST_SAVE": "true",
        },
        "volume": {"container": "/factorio"},
    },
    "rust": {
        "display_name": "Rust",
        "steam_appid": 252490,
        "category": "Survival",
        "summary": "Survival sandbox with monthly wipes; RCON enabled by default.",
        "notes": "Requires at least 8 GB RAM (12+ recommended). Uses web RCON (port 28016). First start downloads ~6 GB of game files.",
        "default_name": "rust",
        "image": "indifferentbroccoli/rust-server-docker:latest",
        "ports": [
            {"container": 28015, "protocol": "udp"},
            {"container": 28015, "protocol": "tcp"},
            {"container": 28016, "protocol": "tcp"},
            {"container": 28082, "protocol": "tcp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "SERVER_NAME": "Rust Server",
            "SERVER_DESCRIPTION": "Managed by Lynx",
            "MAX_PLAYERS": 50,
            "WORLD_SIZE": 3500,
            "SERVER_SEED": 12345,
            "SAVE_INTERVAL": 600,
            "SERVER_PORT": 28015,
            "RCON_PORT": 28016,
            "RCON_PASSWORD": "change-me",
            "APP_PORT": 28082,
            "OXIDE_ENABLED": "false",
            "UPDATE_ON_START": "true",
            "GENERATE_SETTINGS": "true",
            "TZ": "UTC",
        },
        "network_mode": "host",
        "volume": {"container": "/steamcmd/rust"},
        "server_commands": {
            "save": "server.save",
            "stop": "quit",
            "restart": "restart 120 \"Server restarting in 2 minutes\"",
            "broadcast": "say {message}",
            "kick": "kick {player} {reason}",
            "ban": "ban {player} {reason}",
        },
        "game_settings": {
            "config_file": "server/server.cfg",
            "config_format": "keyvalue",
            "settings": [
                {"key": "server.hostname", "label": "Server Name", "type": "string", "default": "Rust Server", "env_var": "SERVER_NAME"},
                {"key": "server.description", "label": "Description", "type": "string", "default": "Managed by Lynx", "env_var": "SERVER_DESCRIPTION"},
                {"key": "server.maxplayers", "label": "Max Players", "type": "int", "min": 1, "max": 500, "default": 50, "env_var": "MAX_PLAYERS"},
                {"key": "server.worldsize", "label": "World Size", "type": "int", "min": 1000, "max": 6000, "default": 3500, "env_var": "WORLD_SIZE"},
                {"key": "server.seed", "label": "World Seed", "type": "int", "min": 0, "max": 2147483647, "default": 12345, "env_var": "SERVER_SEED"},
                {"key": "server.saveinterval", "label": "Save Interval (sec)", "type": "int", "min": 60, "max": 3600, "default": 600, "env_var": "SAVE_INTERVAL"},
                {"key": "server.tickrate", "label": "Tick Rate", "type": "int", "min": 10, "max": 100, "default": 30},
                {"key": "decay.scale", "label": "Decay Scale", "type": "float", "min": 0.0, "max": 10.0, "default": 1.0, "env_var": "DECAY_SCALE"},
            ],
        },
    },
    "satisfactory": {
        "display_name": "Satisfactory",
        "steam_appid": 526870,
        "category": "Simulation",
        "summary": "Co-op factory builder with three exposed UDP ports.",
        "notes": "Back up saves frequently. Requires 8–16 GB RAM. Auto-updates on container restart.",
        "default_name": "satisfactory",
        "image": "wolveix/satisfactory-server:latest",
        "ports": [
            {"container": 7777, "protocol": "udp"},
            {"container": 15000, "protocol": "udp"},
            {"container": 15777, "protocol": "udp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "TZ": "UTC",
            "DEBUG": "false",
        },
        "volume": {"container": "/config"},
    },
    "7_days_to_die": {
        "display_name": "7 Days to Die",
        "steam_appid": 251570,
        "category": "Survival",
        "summary": "Zombie survival crafting with scheduled blood moons and LinuxGSM management.",
        "notes": "Uses LinuxGSM with auto-backups and monitoring. Edit sdtdserver.xml in ServerFiles for advanced config.",
        "default_name": "7d2d",
        "image": "vinanrra/7dtd-server:latest",
        "ports": [
            {"container": 26900, "protocol": "udp"},
            {"container": 26900, "protocol": "tcp"},
            {"container": 26901, "protocol": "udp"},
            {"container": 26902, "protocol": "udp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "TimeZone": "UTC",
            "START_MODE": "1",
            "VERSION": "public",
            "TEST_ALERT": "YES",
            "MONITOR": "NO",
            "BACKUP": "YES",
        },
        "volume": {"container": "/home/sdtdserver"},
        "game_settings": {
            "config_file": "serverfiles/sdtdserver.xml",
            "config_format": "xml-7dtd",
            "settings": [
                {"key": "ServerName", "label": "Server Name", "type": "string", "default": "7 Days to Die Server"},
                {"key": "ServerPassword", "label": "Server Password", "type": "string", "default": ""},
                {"key": "ServerMaxPlayerCount", "label": "Max Players", "type": "int", "min": 1, "max": 64, "default": 8},
                {"key": "GameDifficulty", "label": "Difficulty (0-5)", "type": "int", "min": 0, "max": 5, "default": 2},
                {"key": "DayNightLength", "label": "Day Length (minutes)", "type": "int", "min": 10, "max": 240, "default": 60},
                {"key": "DayLightLength", "label": "Daylight Hours", "type": "int", "min": 1, "max": 24, "default": 18},
                {"key": "LootAbundance", "label": "Loot Abundance %", "type": "int", "min": 25, "max": 400, "default": 100},
                {"key": "LootRespawnDays", "label": "Loot Respawn (days)", "type": "int", "min": 1, "max": 90, "default": 7},
                {"key": "LandClaimSize", "label": "Land Claim Size", "type": "int", "min": 1, "max": 64, "default": 41},
                {"key": "ZombiesRun", "label": "Zombies Run (0=default,1=never,2=always)", "type": "int", "min": 0, "max": 2, "default": 0},
                {"key": "BloodMoonFrequency", "label": "Blood Moon Frequency (days)", "type": "int", "min": 1, "max": 90, "default": 7},
                {"key": "BloodMoonEnemyCount", "label": "Blood Moon Zombie Count", "type": "int", "min": 1, "max": 64, "default": 8},
                {"key": "PlayerKillingMode", "label": "PvP Mode (0=off,1=ally only,2=strangers,3=all)", "type": "int", "min": 0, "max": 3, "default": 0},
                {"key": "EACEnabled", "label": "Anti-Cheat Enabled", "type": "bool", "default": True},
            ],
        },
    },
    "enshrouded": {
        "display_name": "Enshrouded",
        "steam_appid": 1203620,
        "category": "Survival",
        "summary": "Co-op survival action RPG running under Proton.",
        "notes": "Uses Proton. No Steam login needed (anonymous). Volume must be owned by 10000:10000 for bind mounts. Ports 15636 AND 15637 must both be open.",
        "default_name": "enshrouded",
        "image": "sknnr/enshrouded-dedicated-server:latest",
        "ports": [
            {"container": 15637, "protocol": "udp"},
        ],
        "env": {
            "SERVER_NAME": "Enshrouded Server",
            "SERVER_PASSWORD": "",
            "PORT": 15637,
            "SERVER_SLOTS": 16,
            "SERVER_IP": "0.0.0.0",
        },
        "volume": {"container": "/home/steam/enshrouded/savegame"},
        "game_settings": {
            "config_file": "enshrouded_server.json",
            "config_format": "json",
            "settings": [
                {"key": "name", "label": "Server Name", "type": "string", "default": "Enshrouded Server"},
                {"key": "password", "label": "Server Password", "type": "string", "default": ""},
                {"key": "maxPlayers", "label": "Max Players", "type": "int", "min": 1, "max": 16, "default": 16},
                {"key": "ip", "label": "Server IP", "type": "string", "default": "0.0.0.0"},
                {"key": "gamePort", "label": "Game Port", "type": "int", "min": 1024, "max": 65535, "default": 15637},
                {"key": "queryPort", "label": "Query Port", "type": "int", "min": 1024, "max": 65535, "default": 15637},
            ],
        },
    },
    "assetto_corsa": {
        "display_name": "Assetto Corsa",
        "steam_appid": 244210,
        "category": "Simulation",
        "summary": "Dedicated racing server with stracker telemetry.",
        "notes": "⚠️ ARCHIVED IMAGE — this Docker image is no longer maintained (last updated 2019). REQUIRES Steam credentials (STEAM_USER/STEAM_PASSWORD) with Steam Guard DISABLED. May not work with modern SteamCMD.",
        "default_name": "assetto",
        "image": "germanrcuriel/assetto-corsa-server:latest",
        "ports": [
            {"container": 8081, "protocol": "tcp"},
            {"container": 9600, "protocol": "tcp"},
            {"container": 9600, "protocol": "udp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "TZ": "UTC",
            "STEAM_USER": "",
            "STEAM_PASSWORD": "",
            "AC_SERVER_NAME": "Assetto Server",
            "AC_PASSWORD": "",
            "AC_ADMIN_PASSWORD": "change-me",
        },
        "volume": {"container": "/steamapps"},
    },
    "ark_survival_ascended": {
        "display_name": "ARK: Survival Ascended",
        "steam_appid": 2399830,
        "category": "Survival",
        "summary": "UE5 reboot of ARK with high CPU/RAM requirements.",
        "notes": "Peer port is game+1; allow at least 16 GB RAM. IMPORTANT: Run 'sysctl -w vm.max_map_count=262144' on the host or the server will hang on startup.",
        "default_name": "ark-sa",
        "image": "acekorneya/asa_server:latest",
        "ports": [
            {"container": 7777, "protocol": "udp"},
            {"container": 7778, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
            {"container": 37015, "protocol": "tcp"},
        ],
        "env": {
            "SESSION_NAME": "ARK Ascended",
            "SERVER_PASSWORD": "",
            "ADMIN_PASSWORD": "change-me",
            "MAX_PLAYERS": 70,
            "QUERY_PORT": 27015,
            "AUTO_UPDATE": 0,
        },
        "volume": {"container": "/ark-server"},
        "server_commands": {
            "save": "saveworld",
            "stop": "doexit",
            "broadcast": "broadcast {message}",
            "kick": "kickplayer {steamid}",
            "ban": "banplayer {steamid}",
        },
        "game_settings": {
            "config_file": "ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini",
            "config_format": "ini",
            "config_section": "ServerSettings",
            "settings": [
                {"key": "ServerPassword", "label": "Server Password", "type": "string", "default": ""},
                {"key": "ServerAdminPassword", "label": "Admin Password", "type": "string", "default": ""},
                {"key": "MaxPlayers", "label": "Max Players", "type": "int", "min": 1, "max": 70, "default": 70},
                {"key": "DifficultyOffset", "label": "Difficulty", "type": "float", "min": 0.0, "max": 1.0, "default": 0.2},
                {"key": "XPMultiplier", "label": "XP Multiplier", "type": "float", "min": 0.1, "max": 100.0, "default": 1.0},
                {"key": "TamingSpeedMultiplier", "label": "Taming Speed", "type": "float", "min": 0.1, "max": 100.0, "default": 1.0},
                {"key": "HarvestAmountMultiplier", "label": "Harvest Amount", "type": "float", "min": 0.1, "max": 100.0, "default": 1.0},
                {"key": "PlayerCharacterWaterDrainMultiplier", "label": "Water Drain Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0},
                {"key": "PlayerCharacterFoodDrainMultiplier", "label": "Food Drain Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0},
                {"key": "DinoCharacterFoodDrainMultiplier", "label": "Dino Food Drain Rate", "type": "float", "min": 0.1, "max": 5.0, "default": 1.0},
                {"key": "DayCycleSpeedScale", "label": "Day Cycle Speed", "type": "float", "min": 0.1, "max": 10.0, "default": 1.0},
                {"key": "NightTimeSpeedScale", "label": "Night Speed", "type": "float", "min": 0.1, "max": 10.0, "default": 1.0},
                {"key": "bAllowFlyerCarryPvE", "label": "Allow Flyer Carry (PvE)", "type": "bool", "default": False},
            ],
        },
    },
    "the_front": {
        "display_name": "The Front",
        "steam_appid": 2285150,
        "category": "Survival",
        "summary": "PvPvE survival shooter with four exposed service ports.",
        "notes": "Do not append flags after the password flag; server tags limited to five entries.",
        "default_name": "the-front",
        "image": "mcltn/thefrontdedicated:latest",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27016, "protocol": "udp"},
            {"container": 27017, "protocol": "udp"},
            {"container": 27018, "protocol": "udp"},
        ],
        "env": {
            "SERVER_NAME": "The Front Server",
            "SERVER_PASSWORD": "",
            "QUERY_PORT": 27017,
            "SHUTDOWN_PORT": 27018,
            "MAX_PLAYERS": 50,
            "AUTO_UPDATE": 0,
        },
        "volume": {"container": "/config"},
    },
    "dayz": {
        "display_name": "DayZ",
        "steam_appid": 221100,
        "category": "Survival",
        "summary": "Open-world survival shooter via SteamCMD. Requires Steam account.",
        "notes": "REQUIRES Steam credentials (USERNAME/PASSWRD) with Steam Guard DISABLED. Downloads ~20 GB.",
        "default_name": "dayz",
        "image": "ghcr.io/ich777/steamcmd:dayz",
        "ports": [
            {"container": 2302, "protocol": "udp"},
            {"container": 2303, "protocol": "udp"},
            {"container": 27016, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "223350",
            "GAME_PARAMS": "-config=serverDZ.cfg -port=2302 -profiles=profiles",
            "GAME_PORT": 2302,
            "VALIDATE": "false",
            "USERNAME": "",
            "PASSWRD": "",
        },
        "volume": {"container": "/serverdata"},
    },
    "ark_survival_evolved": {
        "display_name": "ARK: Survival Evolved",
        "steam_appid": 346110,
        "category": "Survival",
        "summary": "Classic ARK dedicated server via SteamCMD.",
        "notes": "Downloads ~15 GB on first start. Allow high CPU/RAM for larger maps.",
        "default_name": "ark-se",
        "image": "ghcr.io/ich777/steamcmd:arkse",
        "ports": [
            {"container": 7777, "protocol": "udp"},
            {"container": 7778, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "376030",
            "GAME_PARAMS": "TheIsland?listen?SessionName=ARK-Server?ServerPassword=?ServerAdminPassword=change-me?MaxPlayers=70 -server -log",
            "GAME_PORT": 7777,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
        "server_commands": {
            "save": "saveworld",
            "stop": "doexit",
            "broadcast": "broadcast {message}",
            "kick": "kickplayer {steamid}",
            "ban": "banplayer {steamid}",
        },
    },
    "conan_exiles": {
        "display_name": "Conan Exiles",
        "steam_appid": 440900,
        "category": "Survival",
        "summary": "Survival sandbox in the Exiled Lands via SteamCMD.",
        "notes": "Downloads ~40 GB on first start. Runs under Wine/Proton.",
        "default_name": "conan-exiles",
        "image": "ghcr.io/ich777/steamcmd:conanexiles",
        "ports": [
            {"container": 7777, "protocol": "udp"},
            {"container": 7778, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "443030",
            "GAME_PARAMS": "-log",
            "GAME_PORT": 7777,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
    },
    "squad": {
        "display_name": "Squad",
        "steam_appid": 393380,
        "category": "Shooter",
        "summary": "Tactical FPS with VOIP and large maps.",
        "notes": "Set RCON password; ensure UDP ports are forwarded.",
        "default_name": "squad",
        "image": "cm2network/squad:latest",
        "ports": [
            {"container": 7787, "protocol": "udp"},
            {"container": 27165, "protocol": "udp"},
            {"container": 21114, "protocol": "tcp"},
        ],
        "env": {
            "SERVER_NAME": "Squad Server",
            "SERVER_PASSWORD": "",
            "MAX_PLAYERS": 80,
            "RCON_PASSWORD": "change-me",
        },
        "volume": {"container": "/home/steam/squad-dedicated"},
    },
    "eco": {
        "display_name": "Eco",
        "steam_appid": 382310,
        "category": "Simulation",
        "summary": "Collaborative civilization builder with an economy and laws.",
        "notes": "Downloads ~1.5 GB on first start. Config files are in serverfiles/Configs.",
        "default_name": "eco",
        "image": "ghcr.io/ich777/steamcmd:eco",
        "ports": [
            {"container": 3000, "protocol": "tcp"},
            {"container": 3001, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "739590",
            "GAME_PARAMS": "",
            "GAME_PORT": 3000,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
    },
    "space_engineers": {
        "display_name": "Space Engineers",
        "steam_appid": 244850,
        "category": "Sandbox",
        "summary": "Voxel engineering sandbox with Wine-based dedicated server.",
        "notes": "⚠️ Experimental — runs under Wine with known stability issues. Requires pre-configured world from Windows SE Dedicated Server Tool. Image is ~2 GB. RAM may be capped at 4 GB on some hosts.",
        "default_name": "space-engineers",
        "image": "devidian/spaceengineers:latest",
        "ports": [
            {"container": 27016, "protocol": "udp"},
        ],
        "env": {
            "INSTANCE_NAME": "Dedicated",
            "WINEDEBUG": "-all",
            "TZ": "UTC",
        },
        "volume": {"container": "/appdata/space-engineers"},
    },
    "left4dead2": {
        "display_name": "Left 4 Dead 2",
        "steam_appid": 550,
        "category": "Shooter",
        "summary": "Co-op zombie shooter dedicated server via SteamCMD.",
        "notes": "Downloads ~3 GB on first start. Set RCON password in server.cfg after install.",
        "default_name": "l4d2",
        "image": "ghcr.io/ich777/steamcmd:l4d2",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27015, "protocol": "tcp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "222860",
            "GAME_NAME": "left4dead2",
            "GAME_PARAMS": "+maxplayers 8 +map c1m1_hotel",
            "GAME_PORT": 27015,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
    },
    "terraria": {
        "display_name": "Terraria (Vanilla)",
        "steam_appid": 105600,
        "category": "Sandbox",
        "summary": "Vanilla dedicated Terraria server.",
        "notes": "Single TCP port; for mods use tModLoader entry.",
        "default_name": "terraria",
        "image": "ghcr.io/beardedio/terraria:latest",
        "ports": [
            {"container": 7777, "protocol": "tcp"},
        ],
        "env": {
            "WORLD_NAME": "Dedicated",
            "MAX_PLAYERS": 8,
            "PASSWORD": "",
        },
        "volume": {"container": "/config"},
    },
    "stormworks": {
        "display_name": "Stormworks",
        "steam_appid": 573090,
        "category": "Sandbox",
        "summary": "Search and rescue sandbox with vehicle building. Runs under Wine.",
        "notes": "⚠️ Minimally maintained image with sparse documentation. Uses Wine internally (Windows server exe). First start may take time to initialize.",
        "default_name": "stormworks",
        "image": "bensonjohnson/swserver:latest",
        "ports": [
            {"container": 25564, "protocol": "udp"},
            {"container": 25564, "protocol": "tcp"},
        ],
        "env": {
            "TZ": "UTC",
        },
        "volume": {"container": "/home/steam/.stormworks"},
    },
    "unturned": {
        "display_name": "Unturned",
        "steam_appid": 304930,
        "category": "Survival",
        "summary": "Free-to-play zombie survival with console I/O support.",
        "notes": "Handles stdin/stdout for console. Crash detection with auto-restart built in.",
        "default_name": "unturned",
        "image": "imperialplugins/unturned:latest",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27016, "protocol": "udp"},
        ],
        "env": {
            "SERVER_TYPE": "",
            "TZ": "UTC",
        },
        "volume": {"container": "/home/steam/Unturned"},
    },
    "arma3": {
        "display_name": "Arma 3",
        "steam_appid": 107410,
        "category": "Shooter",
        "summary": "Military sandbox via SteamCMD. Requires Steam account.",
        "notes": "REQUIRES Steam credentials (USERNAME/PASSWRD) with Steam Guard DISABLED. Downloads ~8 GB.",
        "default_name": "arma3",
        "image": "ghcr.io/ich777/steamcmd:arma3",
        "ports": [
            {"container": 2302, "protocol": "udp"},
            {"container": 2303, "protocol": "udp"},
            {"container": 2304, "protocol": "udp"},
            {"container": 2305, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "233780",
            "GAME_PARAMS": "-name=server -config=server.cfg",
            "GAME_PORT": 2302,
            "VALIDATE": "false",
            "USERNAME": "",
            "PASSWRD": "",
        },
        "volume": {"container": "/serverdata"},
    },
    "garrys_mod": {
        "display_name": "Garry's Mod",
        "steam_appid": 4000,
        "category": "Sandbox",
        "summary": "Sandbox Source server via SteamCMD.",
        "notes": "Add a GSLT (Game Server Login Token) for public server listing. Downloads ~5 GB.",
        "default_name": "gmod",
        "image": "ghcr.io/ich777/steamcmd:gmod",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27015, "protocol": "tcp"},
            {"container": 27005, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "4020",
            "GAME_NAME": "garrysmod",
            "GAME_PARAMS": "+maxplayers 32 +map gm_construct",
            "GAME_PORT": 27015,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
    },
    "insurgency_sandstorm": {
        "display_name": "Insurgency: Sandstorm",
        "steam_appid": 581320,
        "category": "Shooter",
        "summary": "Co-op and PvP tactical shooter dedicated server via SteamCMD.",
        "notes": "Downloads ~30 GB on first start. Configure maps via startup arguments.",
        "default_name": "sandstorm",
        "image": "ghcr.io/ich777/steamcmd:insurgency",
        "ports": [
            {"container": 27102, "protocol": "udp"},
            {"container": 27131, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "581330",
            "GAME_PARAMS": "-Port=27102 -QueryPort=27131 -log",
            "GAME_PORT": 27102,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
    },
    "killing_floor_2": {
        "display_name": "Killing Floor 2",
        "steam_appid": 232090,
        "category": "Shooter",
        "summary": "Co-op horde shooter with webadmin via SteamCMD.",
        "notes": "Downloads ~10 GB on first start. Webadmin available on port 8080 after manual config.",
        "default_name": "kf2",
        "image": "ghcr.io/ich777/steamcmd:kf2",
        "ports": [
            {"container": 7777, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
            {"container": 8080, "protocol": "tcp"},
        ],
        "env": {
            "UID": 99,
            "GID": 100,
            "GAME_ID": "232130",
            "GAME_PARAMS": "kf-bioticslab",
            "GAME_PORT": 7777,
            "VALIDATE": "false",
        },
        "volume": {"container": "/serverdata"},
    },
    "mordhau": {
        "display_name": "Mordhau",
        "steam_appid": 629760,
        "category": "Action",
        "summary": "Medieval melee brawler dedicated server.",
        "notes": "Volume dirs must be chmod 777 or owned by the container user. Uses net=host recommended but works with port mapping.",
        "default_name": "mordhau",
        "image": "cm2network/mordhau:latest",
        "ports": [
            {"container": 7777, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
            {"container": 15000, "protocol": "udp"},
        ],
        "env": {
            "SERVER_ADMINPW": "change-me",
            "SERVER_PW": "",
            "SERVER_NAME": "Mordhau Server",
            "SERVER_MAXPLAYERS": 48,
            "SERVER_PORT": 7777,
            "SERVER_QUERYPORT": 27015,
            "SERVER_BEACONPORT": 15000,
        },
        "volume": {"container": "/home/steam/mordhau-dedicated"},
    },
    "tf2": {
        "display_name": "Team Fortress 2",
        "steam_appid": 440,
        "category": "Shooter",
        "summary": "Source-engine TF2 dedicated server.",
        "notes": "Add a GSLT for public server listing. Downloads ~7 GB on first start.",
        "default_name": "tf2",
        "image": "cm2network/tf2:latest",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27015, "protocol": "tcp"},
        ],
        "env": {
            "SRCDS_RCONPW": "change-me",
            "SRCDS_PW": "",
            "SRCDS_MAXPLAYERS": 24,
            "SRCDS_STARTMAP": "cp_badlands",
            "SRCDS_TOKEN": "",
        },
        "volume": {"container": "/home/steam/tf2-dedicated"},
    },
    "vrising": {
        "display_name": "V Rising",
        "steam_appid": 1604030,
        "category": "Survival",
        "summary": "Vampire survival action RPG with dedicated server.",
        "notes": "Query is game+1; keep both UDP ports forwarded. Passworded servers can only be joined via in-game server browser (not Steam).",
        "default_name": "vrising",
        "image": "trueosiris/vrising:latest",
        "ports": [
            {"container": 9876, "protocol": "udp"},
            {"container": 9877, "protocol": "udp"},
        ],
        "env": {
            "TZ": "UTC",
            "SERVERNAME": "V Rising Server",
            "WORLDNAME": "world1",
            "GAMEPORT": 9876,
            "QUERYPORT": 9877,
        },
        "volume": {"container": "/mnt/vrising/persistentdata"},
        "game_settings": {
            "config_file": "Settings/ServerHostSettings.json",
            "config_format": "json",
            "settings": [
                {"key": "Name", "label": "Server Name", "type": "string", "default": "V Rising Server"},
                {"key": "Description", "label": "Description", "type": "string", "default": ""},
                {"key": "Port", "label": "Game Port", "type": "int", "min": 1024, "max": 65535, "default": 9876},
                {"key": "QueryPort", "label": "Query Port", "type": "int", "min": 1024, "max": 65535, "default": 9877},
                {"key": "MaxConnectedUsers", "label": "Max Players", "type": "int", "min": 1, "max": 40, "default": 40},
                {"key": "MaxConnectedAdmins", "label": "Max Admin Slots", "type": "int", "min": 1, "max": 10, "default": 4},
                {"key": "Password", "label": "Server Password", "type": "string", "default": ""},
                {"key": "SaveName", "label": "Save Name", "type": "string", "default": "world1"},
                {"key": "AutoSaveCount", "label": "Auto Save Count", "type": "int", "min": 1, "max": 50, "default": 25},
                {"key": "AutoSaveInterval", "label": "Auto Save Interval (sec)", "type": "int", "min": 30, "max": 1800, "default": 120},
            ],
        },
    },

}


def _load_additional_catalog() -> dict[str, dict]:
    extra_root = Path(__file__).resolve().parent / "data" / "steam_games"
    if not extra_root.exists() or not extra_root.is_dir():
        return {}

    merged: dict[str, dict] = {}
    for entry in sorted(extra_root.glob("*.json")):
        try:
            payload = json.loads(entry.read_text(encoding="utf-8"))
            if isinstance(payload, dict):
                for slug, meta in payload.items():
                    if isinstance(slug, str) and isinstance(meta, dict):
                        merged[slug.lower()] = meta
        except Exception:
            # We skip malformed custom entries
            continue
    return merged


STEAM_GAMES = {slug: meta for slug, meta in BASE_STEAM_GAMES.items()}
for slug, meta in _load_additional_catalog().items():
    STEAM_GAMES[slug] = meta
